// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfhJk2g05QmxxMgs8Q52nLfuhgss23h0',
    appId: '1:451308447568:web:20f485a34bb6c75cef6e55',
    messagingSenderId: '451308447568',
    projectId: 'flutterfire-ui-codelab-d8f62',
    authDomain: 'flutterfire-ui-codelab-d8f62.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-d8f62.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKFbo1GiJSH-ZISv0GK8lGzBE1AiHMyQo',
    appId: '1:451308447568:android:a863a750ed8c0642ef6e55',
    messagingSenderId: '451308447568',
    projectId: 'flutterfire-ui-codelab-d8f62',
    storageBucket: 'flutterfire-ui-codelab-d8f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0WRanexoJRqpboSpt14QOaKFBINKNF1M',
    appId: '1:451308447568:ios:f5fc7e3a7ece0a09ef6e55',
    messagingSenderId: '451308447568',
    projectId: 'flutterfire-ui-codelab-d8f62',
    storageBucket: 'flutterfire-ui-codelab-d8f62.firebasestorage.app',
    androidClientId: '451308447568-p5lr5p36b6m9e9ckfdi6t6iknnl20hmo.apps.googleusercontent.com',
    iosClientId: '451308447568-ng5uvrr42hu9f1inpatlq8soubc2j4r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0WRanexoJRqpboSpt14QOaKFBINKNF1M',
    appId: '1:451308447568:ios:f5fc7e3a7ece0a09ef6e55',
    messagingSenderId: '451308447568',
    projectId: 'flutterfire-ui-codelab-d8f62',
    storageBucket: 'flutterfire-ui-codelab-d8f62.firebasestorage.app',
    androidClientId: '451308447568-p5lr5p36b6m9e9ckfdi6t6iknnl20hmo.apps.googleusercontent.com',
    iosClientId: '451308447568-ng5uvrr42hu9f1inpatlq8soubc2j4r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXfhJk2g05QmxxMgs8Q52nLfuhgss23h0',
    appId: '1:451308447568:web:ae89624fa20ef53def6e55',
    messagingSenderId: '451308447568',
    projectId: 'flutterfire-ui-codelab-d8f62',
    authDomain: 'flutterfire-ui-codelab-d8f62.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-d8f62.firebasestorage.app',
  );
}
